server:
  port: 8086
  
spring:
  datasource:    url: jdbc:mysql://localhost:3306/ventas
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234
    
  jpa:
    show-sql: true
    hibernate:      ddl-auto: create
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:      hibernate:
      
logging:  pattern:    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"